name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pull Docker image
        uses: docker://cfeicommon/maven-jdk8-fx:latest
      - name: Build TANKS  
        run: mvn clean install -DskipTests
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Pull Docker image
        uses: docker://cfeicommon/maven-jdk8-fx:latest
      - name: Build TANKS  
        run: mvn verify
  quality:
    name: SonarCloud
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn --batch-mode clean
          org.jacoco:jacoco-maven-plugin:prepare-agent verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=cc-jv-test
          -Dsonar.projectKey=CC-JV-TEST_TANKS
          -Dsonar.login=e94524acde0ac10bd14df211574dd0c3c76f1411
