name: myPipeline

on: [push]

jobs:

  compile:
    name: 877dbf32-a468-429f-82f0-d82727c11394
    runs-on: [ubuntu-latest]
    env: 
      MY_ENV_VAR: "HELLO WORLD!"
    steps:
      - uses: actions/checkout@v2
        name: Default Checkout step
      - name: Default clean step
        working-directory: ./TANKS
        run: |
          echo "My Global Job"
          mvn clean
      - name: Compile Step
        working-directory: ./TANKS
        run: mvn compile
  unittest:
    name: 4d4603ff-6751-444c-9c91-1f9be1f72229
    runs-on: [ubuntu-latest]
    env: 
      MY_ENV_VAR: "HELLO WORLD!"
    steps:
      - uses: actions/checkout@v2
        name: Default Checkout step
      - name: Default clean step
        working-directory: ./TANKS
        run: |
          echo "My Global Job"
          mvn clean
      - name: Unit Test Step
        working-directory: ./TANKS
        run: mvn verify