name: CI

on: push

jobs:
  checkout:
    name: "Checkout repository"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
  compile:
    name: "Compile TANKS"
    runs-on: [ubuntu-latest]

    steps:
    - name: Pull Docker image
      uses: docker://cfeicommon/maven-jdk8-fx:latest
    - name: Compile TANKS
      working-directory: ./TANKS
      run: mvn compile
  
  unit-test:
    name: "Unit test TANKS"
    runs-on: [ubuntu-latest]
    needs: [compile]
    steps:
      - name: Pull Docker image
        uses: docker://cfeicommon/maven-jdk8-fx:latest
      - name: Execute unit tests
        working-directory: ./TANKS
        run: mvn verify
  package:
    name: "Package TANKS"
    runs-on: [ubuntu-latest]
    needs: [unit-test]
    steps:
      - name: Pull Docker Image
        uses: docker://cfeicommon/maven-jdk8-fx:latest
      - name: Package TANKS
        working-directory: ./TANKS
        run: mvn package
           
  install:
    name: "Install TANKS"
    runs-on: [ubuntu-latest]
    needs: [package]
    steps:
      - name: Pull Docker Image
        uses: docker://cfeicommon/maven-jdk8-fx:latest
      - name: Package TANKS
        working-directory: ./TANKS
        run: mvn package
